### PR TITLE
Basic structure for the site

### PR DESCRIPTION
**Pull request by TaneliR**
Add a basic structure and react boilerplate code for the site
- Basic layout
- Routing
- Bunch of basic styles

Dependencies added:

- react-bootstrap
- bootstrap
- react-router-dom
- @fortawesome/fontawesome-svg-core, @fortawesome/free-solid-svg-icons, @fortawesome/react-fontawesome
- sass

### CODE REVIEW

**Review by monteirocamis — APPROVED** [review]
thank you very much!!! I don ´t know how to resolve the conflicts using the terminal, could you please help me?

**Comment by TaneliR** [comment]
> thank you very much!!! I don ´t know how to resolve the conflicts using the terminal, could you please help me?

I'll resolve them when I get back on my computer 👍

**Comment by TaneliR** [comment]
Okay I merged your main branch, removed my footer and added the one you had merged and did a little cleanup round. It should be ready to be good now.

If you have any questions about my changes don't  hesitate to ask! 

I was afraid I went a little overboard with the size of the PR 😅

**Comment by monteirocamis** [comment]
It´s ok @TaneliR I will open on my local right now to see everthing 💜 
please let me know if you want to continue working in other issues =)

**Comment by TaneliR** [comment]
Ok, I'll see if there's some interesting issues in the future. Didn't get to actualy code almost anything with this, it's mostly just styles and boilerplate code. 😄 

If you don't mind, could you add the `hacktoberfest-accepted` label to this PR if everything looks okay to you 👍

**Comment by monteirocamis** [comment]
image
it is already so beautiful  @TaneliR  !!! thank you !!
I will open now the next features ;)

Congratulations !!

**Pull request merged**
